version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "16"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/SwaroopSPradhan/MicroSim"

[[analyzers]]
name = "ansible"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "shell"
enabled = true